### PR TITLE
Dashboard Listings Tab Accessibility

### PR DESCRIPTION
**Pull request by chasechow7**
## Description

Add accessibility functionality to dashboard listings tabs

- Ability to tab to core tabs (Drafts, Publish Queue, etc.)
- Add keyboard functionality: Ability to select tab using 'Enter'
- Aria Label for screen reader will read: "Dashboard Tab {Name}"
- Aria Label will indicate currently selected tab with "Active Dashboard Tab {Name}"

## Testing
Can test it here: https://d2wo27gatac4jo.cloudfront.net/admin/dashboards

- Turn on screen reader and tab through the core dashboard tabs
- Press Enter to select highlighted tab
- When tabbing to active tab. Can confirm Aria Label indicates this is the active tab

-Added and passed Unit Testing

---

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by trietlu — COMMENTED** [review]
@chasechow7 I did some testing and it looks good

@miguelpdiaz8 Is this the only tab component where we need this change? The section tab doesn't share code with this component right?

**Comment by chasechow7** [comment]
> @chasechow7 I did some testing and it looks good
> 
> @miguelpdiaz8 Is this the only tab component where we need this change? The section tab doesn't share code with this component right?

Ohh... Good call. I think the section tab does share code with this. Instead of hard coding in "dashboard" in the aria label. I'll make sure its generated dynamically so it'll say "Section Tab {name}" when used in section

**Comment by miguelpdiaz8** [comment]
> > @chasechow7 I did some testing and it looks good
> > @miguelpdiaz8 Is this the only tab component where we need this change? The section tab doesn't share code with this component right?
> 
> Ohh... Good call. I think the section tab does share code with this. Instead of hard coding in "dashboard" in the aria label. I'll make sure its generated dynamically so it'll say "Section Tab {name}" when used in section

You also need to add aria-labels for VerticalTabs and VerticalTab components

**Comment by chasechow7** [comment]
> > > @chasechow7 I did some testing and it looks good
> > > @miguelpdiaz8 Is this the only tab component where we need this change? The section tab doesn't share code with this component right?
> > 
> > 
> > Ohh... Good call. I think the section tab does share code with this. Instead of hard coding in "dashboard" in the aria label. I'll make sure its generated dynamically so it'll say "Section Tab {name}" when used in section
> 
> You also need to add aria-labels for VerticalTabs and VerticalTab components

Hmm... Should that be a separate story if we're adding aria labels to the vertical tabs for the Section Widget?

**Comment by chasechow7** [comment]
- Changed out strings to support Translation
- Added variable for container name to support either Section Widget or Dashboard Listing
- Updated Unit Tests

**Review by miguelpdiaz8 — APPROVED** [review]
LGTM

**Pull request merged**
