### PR TITLE
Gtt 1522

### PR DESCRIPTION
**Pull request by PhilTower**
## Description

I added a script and examples to insert examples to the deployed app.

- added examples folder
- added lambda to insert entities into the database and copy files into datasets bucket
- added one examples dashboard
- added readme on how the script works and how to add more.
- updated deployment script to handle language
- updated cft template for new paramter

## Testing

Added unit tests for deployment script.
Ran deployed lambda multiple times to verify in AWS
Setup command line debugging to test locally
Ran deploy.sh several times to check cdk deployment.

Checked inserted examples in app to verify charts are they and look as expected.

Still need to test with the `performance-dashboard-on-aws.template` . CDK synth templates dont work with parameters as expected

## Example Dashboard

* Go to https://d2h803e1awe3zo.cloudfront.net/admin/dashboards
* Open the dashboard
* Verify preview works fine
* Publish the dashboard
* Verify public view works fine
* Verify the https://d2h803e1awe3zo.cloudfront.net/ link to the dashboard works too.

---

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by miguelpdiaz8 — APPROVED** [review]
LGTM

**Review by trietlu — COMMENTED** [review]
@mabreuortega 

It looks good! Couple of questions:

1. in ./.gitignore, we are ignoring node_modules.  Why is there a node_modules folder in the top level folder
2. in widget.ts, why is the change with showWithTabs needed for this story?

**Comment by mabreuortega** [comment]
> @mabreuortega
> 
> It looks good! Couple of questions:
> 
>     1. in ./.gitignore, we are ignoring node_modules.  Why is there a node_modules folder in the top level folder
> 
>     2. in widget.ts, why is the change with showWithTabs needed for this story?

I reverted the gitignore changes, this was added by VSCode.

Regarding the widget.ts this property was used as boolean but the type in the API was a string. I check and everything is working normally due to the fact that the client have it as a boolean already.

**Review by trietlu — APPROVED** [review]
lgtm

**Pull request merged**
