### PR TITLE
Corrects the use of ARIA labels for progress bars

### PR DESCRIPTION
**Pull request by kharbutli-meta**
## Description

GTT-1672: Correct the use of ARIA labels for progress bars by moving it from the "div" section to the "ol" section.

## Testing

* Unit tests: Updated snapshot.
* Ran locally.

---

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by trietlu — COMMENTED** [review]
Can you update the description, looks like the formatting is off.  Also, in testing, did you test on AWS? 

Will approve after confirmation

**Comment by kharbutli-meta** [comment]
Formatting updated.
Yes, tested on AWS account.

**Review by trietlu — APPROVED** [review]
lgtm

**Review by mabreuortega — APPROVED** [review]
LGTM

**Pull request merged**
