### PR TITLE
GTT-1082: UserListing.tsx Localization (en) - partial

### PR DESCRIPTION
**Pull request by DaveOrDavid**
## Description

DropdownMenu, Actions, ResendInvites modified
Added Global for common terms (close, cancel, delete, search)
- other text localization remains, PR for completed steps only.

## Testing

Local testing via `npm run start`
---

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by ferdingler — CHANGES_REQUESTED** [review]
There is a test failing because the text `Resend invite email` no longer matches. I believe the issue is you are using the incorrect label in Line 174, but double check.

**Comment by trietlu** [comment]
@DaveOrDavid Your label UserListingActionsResendInvites is Resend invite emails, which doesn't match Resend invite email

**Comment by DaveOrDavid** [comment]
Ending up with a merge conflict and pushed the conflict
a3d883d is the fix I've applied

**Comment by trietlu** [comment]
Hi @DaveOrDavid Looks like this PR picked up changes that were already committed.  I'd recommend that you apply your changes to a new clean PR

**Comment by ferdingler** [comment]
Rebasing your branch is always the best approach rather than merging it. 

```
git checkout GTT-1082-3
git pull origin mainline --rebase

# Resolve conflicts if any

git push origin +GTT-1082-3
```

**Pull request closed without merging**
