### PR TITLE
Localization in DraftTabs, PublishQueueTab, PublishedTab (en)

### PR DESCRIPTION
**Pull request by DaveOrDavid**
## Description
English Localization to Components:

1) DraftTabs.tsx to english
2) PublishQueueTab to english
3) PublishedTab to english
4) en/translation.json pairs added

## Testing

Local front end testing via `npm start`
---

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by ajmokotoff — DISMISSED** [review]
Nice job!

**Comment by trietlu** [comment]
Nice work @DaveOrDavid .  You'll need to install prettier in your VSCode environment by creating .vscode/settings.json in the root of your project with the content

```
"editor.formatOnSave": true
```

**Review by ferdingler — CHANGES_REQUESTED** [review]
Something looks strange with the Pull Request. It shows 94,262 lines of code added.

**Comment by ajmokotoff** [comment]
> Something looks strange with the Pull Request. It shows 94,262 lines of code added.

Did you install prettier via NPM? There is one built in that you can use in VSCode.

**Comment by ferdingler** [comment]
> > Something looks strange with the Pull Request. It shows 94,262 lines of code added.
> 
> Did you install prettier via NPM? There is one built in that you can use in VSCode.

Yes, do this. Install the Prettier extension in Visual Studio Code and then create a file `.vscode/settings.json` in the root of your project with this content: 

```json
{
  "editor.formatOnSave": true,
  "editor.defaultFormatter": "esbenp.prettier-vscode",
}

```

**Comment by trietlu** [comment]
Hi @DaveOrDavid , @ajmokotoff or I will help you with the PR tomorrow.  Looks like you pulled in some extra files with the installation of prettier

**Comment by DaveOrDavid** [comment]
> > Something looks strange with the Pull Request. It shows 94,262 lines of code added.
> 
> Did you install prettier via NPM? There is one built in that you can use in VSCode.

Yes, I installed via NPM. We can talk tomorrow.

**Pull request closed without merging**
