### PR TITLE
GTT-368: Add drag and drop for widgets list

### PR DESCRIPTION
**Pull request by miguelpdiaz8**
## Description

Add drag and drop for widgets list.

## Testing

Updated unit tests.

---

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by trietlu — APPROVED** [review]
lgtm.  

@miguelpdiaz8 please copy the [license](https://github.com/react-dnd/react-dnd/blob/main/LICENSE)  for react-dnd to the bottom of the [THIRD-PARTY-LICENSES](https://github.com/awslabs/performance-dashboard-on-aws/blob/mainline/THIRD-PARTY-LICENSES) file also

**Comment by trietlu** [comment]
Also, does the drag and drop work with touch screen? (Not a priority, as we've said the editing experience should be done on the desktop

**Comment by miguelpdiaz8** [comment]
> Also, does the drag and drop work with touch screen? (Not a priority, as we've said the editing experience should be done on the desktop

I'll do it in a separate story

**Comment by trietlu** [comment]
> I'll do it in a separate story

@miguelpdiaz8 Just demo what you have to get Jason's feedback.  If we need to, we can do another story in a future sprint

**Pull request merged**
