### PR TITLE
GTT-1581: Add accessible labels to the Check Data column checkboxes

### PR DESCRIPTION
**Pull request by chasechow7**
## Description

Added accessibility labels to the checkboxes so the text-to-speech screen reader will output the column header name

## Testing

- Updated and ran Unit Tests
- Checked functionality with Screen Reader extension

---

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by trietlu** [comment]
@chasechow7 how are we testing that the aria label is present?

**Comment by chasechow7** [comment]
> @chasechow7 how are we testing that the aria label is present?

I checked the aria-label is present under the Elements tab when inspecting the page
image

**Comment by miguelpdiaz8** [comment]
They are also present in the snapshot tests

**Comment by trietlu** [comment]
Bad Triet, read it too fast :-)

**Review by trietlu — APPROVED** [review]
lgtm

**Pull request merged**
