### PR TITLE
GTT-309 Admin landing page

### PR DESCRIPTION
**Pull request by miguelpdiaz8**
## Description

GTT-309 Admin landing page

## Testing

You can test it here: https://migdizn.badger.wwps.aws.dev/admin

---

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ferdingler** [comment]
Looks like I no longer have a username in your personal environment @miguelpdiaz8

**Comment by miguelpdiaz8** [comment]
> Looks like I no longer have a username in your personal environment @miguelpdiaz8

You should have received an email yesterday. But I'll resend the invite for all of you now.

**Comment by miguelpdiaz8** [comment]
> > Looks like I no longer have a username in your personal environment @miguelpdiaz8
> 
> You should have received an email yesterday. But I'll resend the invite for all of you now.

Done

**Comment by ferdingler** [comment]
Thanks

**Review by ferdingler — APPROVED** [review]

**Pull request merged**
